export const APP_CHANGE = "APP_CHANGE";
export const APP_CLEAR = "APP_CLEAR";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const TOGGLE_THEME = "TOGGLE_THEME";
export const OPEN_CONTENT = "OPEN_CONTENT";
export const CLOSE_CONTENT = "CLOSE_CONTENT";
export const TOGGLE_PLAYER = "TOGGLE_PLAYER";
export const TOGGLE_AUDIO = "TOGGLE_AUDIO";
export const CHANGE_VOLUME_AUDIO = "CHANGE_VOLUME_AUDIO";

export const USER_CHANGE = "USER_CHANGE";
export const USER_CLEAR = "USER_CLEAR";
export const NOTIFY_CHANGE = "NOTIFY_CHANGE";
export const NOTIFY_CLEAR = "NOTIFY_CLEAR";